openapi: 3.0.1
info:
  title: TidyTask REST API
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Obtener todas las tareas
      operationId: getTaskList
      tags:
        - Tasks
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Crear una nueva tarea
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea creada

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        completed:
          type: boolean
        date:
          type: string
          format: date-time
        hour:
          type: string
          format: time
